### ISSUE TITLE
provide a build?

### ISSUE THREAD

**Issue by xloem** [meganz/jodid25519#9]
I'd like to use ed25519 from a web browser, but there is no standard .js file to include.  It would be nice if the project included a prepackaged script.

**Comment by pohutukawa** [comment]
I'd recommend to use TweetNaCl.js. jodid25519 is not maintained any more, and it's not fully constant time. Besides that, TweetNaCl.js also performs better and has likely seen more code review.

```
Chromium 44.0.2403 (Ubuntu):

Curve25519 multiply call jodid25519: 3.50 ms
Curve25519 multiply call TweetNaCl: 1.58 ms
signature jodid25519: 15.73 ms
signature TweetNaCl: 7.28 ms
verification jodid25519: 27.10 ms
verification TweetNaCl: 14.04 ms

Firefox 40.0.0 (Ubuntu):

Curve25519 multiply call jodid25519: 5.61 ms
Curve25519 multiply call TweetNaCl: 1.34 ms
signature jodid25519: 26.99 ms
signature TweetNaCl: 6.10 ms
verification jodid25519: 42.62 ms
verification TweetNaCl: 11.12 ms
```
